basePath: /
host: localhost:9000
info:
  contact:
    email: yono.tri@gmail.com
    name: API Support
  description: This is a documentation service for todo apps
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Todos API
  version: "1.0"
paths:
  /todos:
    get:
      consumes:
      - application/json
      description: create new todos with input payload.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - getTodos
swagger: "2.0"
